services:
  # container 1
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      # MYSQL_USER (root) est créé automatiquement au lancement de ce service
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    ports:
      - "3307:3306"  # Host port : 3307 (3306 étant pris par MySQL en local)
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  # container 2
  init-db:
    build: .  # Reprend l'image définie dans Dockerfile
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./data/processed:/app/data/processed  # <-- bind mount
    command: ["python", "db/init_db.py"]  # Remplace la ligne CMD dans le Dockerfile afin de lancer init_db.py
    profiles: ["tools"]  # init-db ne sera pas lancé avec docker compose up, mais reste exécutable via docker compose run init-db

  # container 3
  mlflow:
    build: .
    restart: unless-stopped
    ports:
      - "5001:5000"
    volumes:
      - mlflow_data:/mlflow-data
    command: >  # Démarre le serveur MLflow
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:////mlflow-data/mlflow.db
      --default-artifact-root /mlflow-data/artifacts
      --allowed-hosts "*"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 5s
      timeout: 5s
      retries: 10

  # container 4
  api:
    build: .
    restart: unless-stopped
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
      MLFLOW_TRACKING_URI: http://mlflow:5000  # requis pour /training et /predict (modèles chargés depuis MLflow)
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
      mlflow:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 5s
      timeout: 5s
      retries: 10

  # container 5
  airflow-db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      timeout: 5s
      retries: 10

  # container 6
  airflow:
    image: apache/airflow:2.10.4
    restart: unless-stopped
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW_CONN_API_CONNECTION: 'http://api:8000'
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - airflow_data:/opt/airflow
    ports:
      - "8081:8080"
    depends_on:
      airflow-db:
        condition: service_healthy
      api:
        condition: service_healthy
    command: standalone
    # Mode "tout-en-un" (webserver + scheduler + triggerer) — pratique pour un seul conteneur,
    # mais non recommandé pour un déploiement de production à grande échelle

# Les volumes déclarés sont indépendants des containers ci-dessus
volumes:
  mysql_data:
  mlflow_data:
  airflow_db_data:
  airflow_data: